name: Job Application Form
description: Apply for a position at Holdex.
title: "[Position] Firstname Lastname"
labels: ["job-application"]

body:
  - type: input
    id: first_name
    attributes:
      label: "First Name"
      placeholder: "Enter your first name"
    validations:
      required: true

  - type: input
    id: last_name
    attributes:
      label: "Last Name"
      placeholder: "Enter your last name"
    validations:
      required: true

  - type: input
    id: telegram
    attributes:
      label: "Telegram"
      placeholder: "Enter your Telegram Username"
    validations:
      required: true
  
  - type: input
    id: source
    attributes:
      label: "How did you find out about this job?"
      placeholder: "Google, referral, X, Behance, etc."
    validations:
      required: false
 
  - type: input
    id: portfolio
    attributes:
      label: "Link to Portfolio"
      description: "Enter a valid URL. Example: [https://your-portfolio.com](https://your-portfolio.com)"
      placeholder: "https://your-portfolio.com"
    validations:
      required: true
      pattern: "https?://.*"

  - type: input
    id: linkedin
    attributes:
      label: "Link to LinkedIn Profile"
      description: "Enter a valid LinkedIn profile URL. Example: [https://linkedin.com/in/yourprofile](https://linkedin.com/in/yourprofile)"
      placeholder: "https://linkedin.com/in/yourprofile"
    validations:
      required: true
      pattern: "https?://.*"
  
  - type: markdown
    attributes:
      value: |
        
        ⚠️ **Ensure your portfolio and LinkedIn links include `https://` to be clickable.**
        
  
  - type: textarea
    id: description
    attributes:
      label: "Short Description"
      description: "Briefly introduce yourself and your experiences. Show us your best achievements and explain how you're the best fitting candidate for the position."
    validations:
      required: true

  - type: dropdown
    id: position
    attributes:
      label: "Application Position"
      options:
        - "UX/UI Designer"
        - "UX/UI Engineer"
        - "Full-Stack Engineer"
        - "DevOps Engineer"
        - "GoLang Engineer"
        - "Data Scientist"
        - "Python Engineer"
        - "Developer Relations (DevRel)"
        - "Senior Smart Contract Developer"
        - "Actuarial Advisor"
    validations:
      required: true
